address=/cloud.merox.dev/100.72.22.38
address=/vscode.cloud.merox.dev/100.72.22.38
address=/portainer.cloud.merox.dev/100.72.22.38
address=/glances.cloud.merox.dev/100.72.22.38
address=/pihole.cloud.merox.dev/100.72.22.38
address=/traefik.cloud.merox.dev/100.72.22.38
address=/homepage.cloud.merox.dev/100.72.22.38
