services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "32769:9001"  # Console
      - "32768:9000"  # API
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    command: server /data --console-address ":9001"
    volumes:
      - type: volume
        source: adf4aa145fa17913684e3b4714935a0fd5b93bedcddff4b4edaf66adb1741318
        target: /data
      - type: volume
        source: 934ae7ade006ab0218965bbfb7f5f49c9c1eb21472364d1bd2bb9b77e5a29c56
        target: /root/.minio
    networks:
      network-cloud-merox:
        ipv4_address: 172.25.10.60
    labels:
      - "traefik.enable=true"
      # Console UI
      - "traefik.http.routers.minio-console.rule=Host(`minio.cloud.merox.dev`)"
      - "traefik.http.routers.minio-console.entrypoints=https"
      - "traefik.http.routers.minio-console.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      # API S3
      - "traefik.http.routers.minio-api.rule=Host(`s3.cloud.merox.dev`)"
      - "traefik.http.routers.minio-api.entrypoints=https"
      - "traefik.http.routers.minio-api.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

volumes:
  adf4aa145fa17913684e3b4714935a0fd5b93bedcddff4b4edaf66adb1741318:
    external: true
  934ae7ade006ab0218965bbfb7f5f49c9c1eb21472364d1bd2bb9b77e5a29c56:
    external: true

networks:
  network-cloud-merox:
    external: true 
